Main Code Testing
uofu-emb/2024-lab2-varun-disha pull request #1
Opened 2024-09-23 06:00 UTC by VarunBhavya

Integration of test code to evaluate the functionality and behavior of the main code

2024-09-23 19:26 UTC, mtthwm requested changes
A couple things:
1. The code is very thoroughly commented, but I think you could probably focus more on describing the "bigger picture" of what the code is doing.
2. I'm a little confused by the test.c. It seems like you are basically copying the code over from blink.c rather than extracting that logic into functions which can be called from both the blink function and the tests. In a way that seems to defeat the purpose of testing, because discrepancies between the logic in the test and the actual code could easily come up. I'd maybe suggest reviewing the section on rewriting code for testability.

2024-09-24 02:56 UTC, AwsomeStar123456 requested changes
I agree with what my partner said. The code in test.c looks like it is just the code in the main file being copied over into test.c. I believe instead the methods used in the actual implementation should be called in test.c in order to be tested. Since you don't want to have delays and stuff in test.c I recommend you take out the important functionality into a separate method to test it.

2024-09-28 03:19 UTC, AwsomeStar123456 approved these changes
Looks good.

2024-10-02 18:47 UTC, mtthwm approved these changes

2024-10-02 19:07 UTC, merged